services:
  mongo-rs1:
    container_name: mongo-rs1
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./scripts:/scripts
    networks:
      - mongo-network
    ports:
      - "27017:27017"
    depends_on:
      - mongo-rs2
      - mongo-rs3
    links:
      - mongo-rs2
      - mongo-rs3
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo-rs2:
    container_name: mongo-rs2
    image: mongo:latest
    restart: unless-stopped
    networks:
      - mongo-network
    ports:
      - "27018:27017"
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo-rs3:
    container_name: mongo-rs3
    image: mongo:latest
    restart: unless-stopped
    networks:
      - mongo-network
    ports:
      - "27019:27017"
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

networks:
  mongo-network:
    driver: bridge